server:
  servlet:
    context-path: /EmployeePortalBoot
  port: 8005
spring:
  datasource: 
    url: jdbc:mysql://localhost/employeeportal
    username: root
    password: 1234
    driver-class-name : com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
